//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeChaser.WpfShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeChaser.WpfShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Node Caption=&quot;Root&quot; Probability=&quot;1&quot;&gt;
        ///      &lt;Node Caption=&quot;a&quot; Probability=&quot;0.02&quot; allText=&quot;a&quot; cumulative=&quot;0.0159&quot; &gt;
        ///        &lt;Node Caption=&quot;.&quot; Probability=&quot;0.03&quot; allText=&quot;a .&quot; cumulative=&quot;0.0005&quot; /&gt;
        ///        &lt;Node Caption=&quot;better&quot; Probability=&quot;0.02&quot; allText=&quot;a better&quot; cumulative=&quot;0.0003&quot; /&gt;
        ///        &lt;Node Caption=&quot;bit&quot; Probability=&quot;0.04&quot; allText=&quot;a bit&quot; cumulative=&quot;0.0006&quot; /&gt;
        ///        &lt;Node Caption=&quot;couple&quot; Probability=&quot;0.08&quot; allText=&quot;a couple&quot; cumulative=&quot;0.0013&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MockData {
            get {
                return ResourceManager.GetString("MockData", resourceCulture);
            }
        }
    }
}
